### ISSUE TITLE
Order certificate fails when changing to wildcard certificate

### ISSUE THREAD

**Issue by phelgren** [porunov/acme_client#11]
Z:\home\pete\le_java>java -jar acme_client.jar --version
Porunov Java ACME Client (PJAC) v3.0.0

Z:\home\pete\le_java>java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

I created a wildcard cert for a new domain back in August with no problems at all.  I was also able to renew an existing certificate on a non-wildcard cert (petesworkshop.com)  Today I decided to create a new wildcard for petesworkshop.com and created a csr in exactly the same way I did for my successful wildcard domain.  

The decoded CSR has this:

Common Name: petesworkshop.com
Subject Alternative Names: *.petesworkshop.com
Organization: Value Added Software
Locality: San Antonio
State: Texas
Country: US

When I order the certificate I get this error:
{"failed_domains":["*.petesworkshop.com"],"status":"error"}

The log shows:
018-11-08 11:18:03 ERROR com.jblur.acme_client.command.certificate.OrderCertificateCommand:56 - Cannot process authorization https://acme-v02.api.letsencrypt.org/acme/authz/xpmEGKjVOv-U1yMMLfVNwWQ7rCpYRU5DPJbs0kWgEMA with domain *.petesworkshop.com
java.lang.NullPointerException: null
	at com.jblur.acme_client.command.certificate.CertificateCommand.writeChallengeByAuthorization(CertificateCommand.java:119)
	at com.jblur.acme_client.command.certificate.OrderCertificateCommand.commandExecution(OrderCertificateCommand.java:54)
	at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:47)
	at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecutor.java:123)
	at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:65)
	at com.jblur.acme_client.Application.main(Application.java:65)

So, did I miss a step somewhere?  Your wildcard example uses DNS01 and in my case I am using HTTP01.  Is that the issue?  Command looks like this:

java -jar acme_client.jar --command order-certificate -a Z:/home/pete/certs/le_pub_key/le_account.key -w z:/etc/pjac/certdir -c z:/home/pete/certs/csr/petesworkshop.csr --well-known-dir Z:/www/petes/htdocs/letsencrypt-challenges/.well-known/acme-challenge --one-dir-for-well-known

Thanks

**Comment by porunov** [comment]
@phelgren Hello,

Letsencrypt don't allow to use HTTP challenges for wildcard certificates. Use DNS instead of it.
I have a tutorial here: https://github.com/porunov/acme_client/wiki/Get-a-wildcard-certificate

For additional information you can look at this thread: https://community.letsencrypt.org/t/wildcard-certificates-coming-january-2018/37567/26

Regards

**Comment by phelgren** [comment]
Really sorry.  You even put it in the Wiki statement and it went right past me:
"Let's Encrypt doesn't allow to use HTTO01 challenge for wildcard certificates that is why we use DNS01 challenge in this scenario."

I'll use DNS01.  Thanks
