### ISSUE TITLE
it is possible to add cert end key for different keystore ?

### ISSUE THREAD

**Issue by msokolowskihbz** [porunov/acme_client#7]
I have OpenFire (XMPP/Jabber) serwer on windows, and i need to add letsencrypt cert.

There are instructions on web ( https://community.letsencrypt.org/t/using-cert-in-openfire-xmpp-server/10676/14 ) and ( http://download.igniterealtime.org/openfire/docs/latest/documentation/ssl-guide.html ).

But it will be much simpler to just add option to add cert to Java keystore.

**Comment by porunov** [comment]
Hello @msokolowskihbz ,<br>
Do you need to import letsencrypt's certificate to your JRE Certificate Store?<br>
If yes there is a solution described here:<br>
http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html

**Comment by msokolowskihbz** [comment]
It's not the case, i need to tu put generated certificate to other keystore ( "C:\Program Files (x86)\Openfire\resources\security\keystore" ) and it wille be nice if i can skip two steps:
1. conversion from PEM to PKCS12 (using **openssl**)
2. importing generated PKCS12 to keystore (using java **keytool**)

**Comment by msokolowskihbz** [comment]
Sadly i don't know how to program in Java.
