### ISSUE TITLE
Request: To Upgrade the acme4j 

### ISSUE THREAD

**Issue by Markandayan1518** [porunov/acme_client#8]
Now Let’s Encrypt start to support the **Wildcard Certificates**

**Comment by porunov** [comment]
Planned to the release 2.2.0

**Comment by Markandayan1518** [comment]
thanks a lot for considered my request

**Comment by porunov** [comment]
You are welcome!
Just let this issue to be opened till the feature is implemented.

**Comment by phelgren** [comment]
I took a look at this myself and would REALLY like to see an update.  Unfortunately, the acme4j project isn't documented very well when it came to upgrading from the 1.0 to the 2.0 client and exactly what changed and how.  I may continue to try to figure out what to upgrade and how (some looks easy but some of it I didn't see a quick fix).  I'll continue to review progress and IF i figure it out and it works, I'll put in a pull request.  But, the original author can probably do it quicker than I can

**Comment by porunov** [comment]
@phelgren Hello,
It seems that the upgrade process isn't a simple process and will cause a lot of changes. Right now I am a little bit busy, but I will try to find some time next week. If you can make a PR it would be awesome.

**Comment by porunov** [comment]
The update from acme v1 to acme v2 have some breaking changes (those protocols have a little bit different certificate generation flow).
Particularly in this client there will be removed two commands (`renew-certificate` and `update-agreement`). Also the command `authorize-domains` is now changed to  `order-certificate` command. 

I will push the related PR after I manage to update the documentation. 

Anyone who would like to test the new client can use the following branch:
https://github.com/porunov/acme_client/tree/acme2

You can use `--help` for additional information.

**Comment by phelgren** [comment]
Worked like a charm.  The command changes meant I needed to change up my scripts but I really appreciated the update.  Sorry I could have been of more help...
